/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tsurugidb_tsubakuro_channel_ipc_IpcLink */

#ifndef _Included_com_tsurugidb_tsubakuro_channel_ipc_IpcLink
#define _Included_com_tsurugidb_tsubakuro_channel_ipc_IpcLink
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tsurugidb_tsubakuro_channel_ipc_IpcLink_RESPONSE_NULL
#define com_tsurugidb_tsubakuro_channel_ipc_IpcLink_RESPONSE_NULL 0L
#undef com_tsurugidb_tsubakuro_channel_ipc_IpcLink_RESPONSE_PAYLOAD
#define com_tsurugidb_tsubakuro_channel_ipc_IpcLink_RESPONSE_PAYLOAD 1L
#undef com_tsurugidb_tsubakuro_channel_ipc_IpcLink_RESPONSE_BODYHEAD
#define com_tsurugidb_tsubakuro_channel_ipc_IpcLink_RESPONSE_BODYHEAD 2L
#undef com_tsurugidb_tsubakuro_channel_ipc_IpcLink_RESPONSE_CODE
#define com_tsurugidb_tsubakuro_channel_ipc_IpcLink_RESPONSE_CODE 3L
/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_IpcLink
 * Method:    openNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_IpcLink_openNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_IpcLink
 * Method:    sendNative
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_IpcLink_sendNative
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_IpcLink
 * Method:    awaitNative
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_IpcLink_awaitNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_IpcLink
 * Method:    getInfoNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_IpcLink_getInfoNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_IpcLink
 * Method:    receiveNative
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_IpcLink_receiveNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_IpcLink
 * Method:    isAliveNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_IpcLink_isAliveNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_IpcLink
 * Method:    closeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_IpcLink_closeNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_IpcLink
 * Method:    destroyNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_IpcLink_destroyNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
