/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl */

#ifndef _Included_com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl
#define _Included_com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl
 * Method:    createNative
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl_createNative
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl
 * Method:    getChunkNative
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl_getChunkNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl
 * Method:    disposeUsedDataNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl_disposeUsedDataNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl
 * Method:    isEndOfRecordNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl_isEndOfRecordNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl
 * Method:    closeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_sql_ResultSetWireImpl_closeNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
