/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tsurugidb_tsubakuro_channel_ipc_NativeLibrary */

#ifndef _Included_com_tsurugidb_tsubakuro_channel_ipc_NativeLibrary
#define _Included_com_tsurugidb_tsubakuro_channel_ipc_NativeLibrary
#ifdef __cplusplus
extern "C" {
#endif
#undef com_tsurugidb_tsubakuro_channel_ipc_NativeLibrary_DEFAULT_VERIFY_VERSION
#define com_tsurugidb_tsubakuro_channel_ipc_NativeLibrary_DEFAULT_VERIFY_VERSION 1L
/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_NativeLibrary
 * Method:    getNativeLibraryVersionNative
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_NativeLibrary_getNativeLibraryVersionNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
