/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl */

#ifndef _Included_com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl
#define _Included_com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl
 * Method:    getConnectorNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl_getConnectorNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl
 * Method:    requestNative
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl_requestNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl
 * Method:    waitNative
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl_waitNative__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl
 * Method:    waitNative
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl_waitNative__JJJ
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl
 * Method:    checkNative
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl_checkNative
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl
 * Method:    closeConnectorNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_tsurugidb_tsubakuro_channel_ipc_connection_IpcConnectorImpl_closeConnectorNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
