/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nautilus_technologies_tsubakuro_HelloJNI */

#ifndef _Included_com_nautilus_technologies_tsubakuro_HelloJNI
#define _Included_com_nautilus_technologies_tsubakuro_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nautilus_technologies_tsubakuro_HelloJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_nautilus_1technologies_tsubakuro_HelloJNI_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
